baseURL = "https://freeman-congroo.vercel.app/"
languageCode = "en-us"
title = "Freeman Congroo"
theme = "personal-web"
copyright="© David Chou"
googleAnalytics = ""
enableEmoji=true
enableRobotsTXT=true
pygmentsUseClasses=true
pygmentsCodeFences=true

[params.intro]
  main = "Welcome! 🧐"
  sub = " "

[params.main]
  latestPublishHeader = "Latest"

[taxonomies]
  design = "designs"
  tech = "techs"

[blackfriday]
  hrefTargetBlank = true

[params]
  breadcrumb = true
  accentColor = "#FD3519"
  mainSections = ['experiences']

[params.notFound]
  gopher = "/images/gopher.png" # checkout https://gopherize.me/
  h1 = '404'
  p = "It seems that this page doesn't exist."

[params.sections]
  # Define how your sections will be called
  # when automatically pulled. For instance in the 404 page
  post = "article"
  portfolio = "project"

[params.sidebar]
  backgroundImage = '' # header background image - default "/images/default_sidebar.jpg" - Photo by Tim Marshall on Unsplash
  gradientOverlay = '' # default: rgba(0,0,0,0.4),rgba(0,0,0,0.4)
  logo = "/images/avatar.png" # - default "/images/edna-west.jpg"
[params.assets]
  favicon = ""
  customCSS = ""

[params.social]
  github = "https://github.com/davidchou93"

[params.contact]
  email = "david.chou93@gmail.com"
  text= "✉️CONTACT ME" # text of the contact link in the sidebar. If email params.contact.email is defined


[menu]

[[menu.main]]
  identifier = "about"
  name = "About"
  title = "About section"
  url = "/about/"
  weight = -120

[[menu.main]]
  identifier = "experiences"
  name = "Experiences"
  title = "Experiences"
  url = "/experiences/"
  weight = -110

[[menu.main]]
  identifier = "blogs"
  name = "Posts"
  title = "Blogs section"
  url = "/posts/"
  weight = -100

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = true
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.twitter]
    disable = true
    enableDNT = true
    simple = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true